language: node_js

node_js:
  - "18"
  - "20"
  - "22"

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run check
  - npm run build
  - test -f dist/index.js || (echo "Build output not found" && exit 1)

notifications:
  email:
    on_success: change
    on_failure: always
